### ISSUE TITLE
Does not support middle initials for some cases

### ISSUE THREAD

**Issue by Cloudmersive** [binaryfog/NameParser#15]
Examples that are failing:

"Mr. Jon A. van der Waal Jr."
"Mr. Jon A. Waal Jr."
"James A Adams"

**Comment by binaryfog** [comment]
Extra patterns has been added in v2.4 for handling these cases : 
"Mr. Jon A. van der Waal Jr."
"Mr. Jon A. Waal Jr."

For "James A Adams" , it is parsed as LastName = "A Adams " because "A" is a prefix for last names ; Although "James A. Adams" is parsed as LastName= Adams and MiddleName = "A." .
