### ISSUE TITLE
Middle name with hyphens

### ISSUE THREAD

**Issue by craigbridges** [binaryfog/NameParser#18]
Hi, I have been using your name parser without any issues for just over a year and it's been great, thanks!

However, I recently came across an edge case name **'Mary Sarah-Jane Lucy'** which the parser does not handle correctly.

The issue seems to be the fact that the middle name contains hyphens. Do you think this is something that could be supported?

**Comment by binaryfog** [comment]
I'll look into it and I'll let you know. Thanks for letting me know.

**Comment by ianroof** [comment]
Hello,

I would also like to see if this can be supported. We ran into an example: Samantha Zhou-Yun Chou

**Comment by binaryfog** [comment]
Fixed in version 3.2.3 . I'm sorry that it took that long.

**Comment by craigbridges** [comment]
No problem, thanks for fixing the issue :)
