### ISSUE TITLE
Cannot parse LAST NAME, FIRST NAME if last name contains hyphen.

### ISSUE THREAD

**Issue by sloscialo** [binaryfog/NameParser#22]
Tested against latest version (3.2.0).

Tried the following in LinqPad:
```
	var full = "Esquivel-Moreno, Maria Delores";
	var t = new FullNameParser(full);
	t.Parse();
	t.Dump();
```

The dump showed no results.
![image](https://user-images.githubusercontent.com/3219318/121408571-8e6b3000-c92e-11eb-9cd4-41bbb3cc0705.png)

**Comment by binaryfog** [comment]
Fixed in the version 3.2.1 . Thanks for reporting it .
